name: flutter_easy_form
description: A easy way to build forms with Flutter.
version: 0.0.1-rc
repository: https://github.com/hjJunior/flutter-easy-form

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
